=begin comment

Marketcheck Cars API

<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('marketcheck_api_sdk_perl::DealerApi');

my $api = marketcheck_api_sdk_perl::DealerApi->new();
isa_ok($api, 'marketcheck_api_sdk_perl::DealerApi');

#
# dealer_search test
#
my @dealer_id = (1016810, 1016017, 1016710, 1017138, 1016732);
my @radius = (20, 30, 50);
my @hoh=( {   'latitude'=>35,
    'longitude'=>-90,
    {'radius'=>{'20'=>126,
        '30'=>228,
        '50'=>255
    }
    }
},
    {   'latitude'=>40,
        'longitude'=>-80,
        {'radius'=>{'20'=>25,
            '30'=>97,
            '50'=>359
        }
        }
    }
);


{
    my $limit = 10;
    my $i =0;
    foreach my $hsh (@hoh) {
        my $lower_limit;
        my $upper_limit;
        $lower_limit = $hsh->{radius}{$radius[$i]} - (($limit * $latlong->{radius}{$radius[$i]})/100);
        $upper_limit = $hsh->{radius}{$radius[$i]} + (($limit * $latlong->{radius}{$radius[$i]})/100);
        my $latitude = $hsh->{latitude};  # replace NULL with a proper value
        my $longitude = $latlon->{longitude}; # replace NULL with a proper value
        my $radius = $latlong->{radius};    # replace NULL with a proper value
        my $api_key = undef;   # replace NULL with a proper value
        my $result = $api->dealer_search(latitude => $latitude, longitude => $longitude, radius => $radius, api_key => $api_key);
        my $apis_daeler_cnt = $result->{num_found};
        cmp_ok( $apis_daeler_cnt, '<=', $upper_limit);
        cmp_ok( $apis_daeler_cnt, '>=', $lower_limit);
    }
}

1;
